### PR TITLE
Ds/database

### PR DESCRIPTION
**Pull request by djsong15**
- Update package (install dotenv and cors packages)
- Update route exports/imports
- listingController method now reads and returns data from postgres db
  - check by making GET request to /listing, server should log an array of entries from db

### CODE REVIEW

**Review by albhu24 — APPROVED** [review]
good merge

**Review by basselfares — APPROVED** [review]
PR approved

**Review by Dwijesek — APPROVED** [review]
Cool

**Review by Dwijesek — APPROVED** [review]
cool

**Pull request merged**
